### ISSUE TITLE
failed to initialize postgres

### ISSUE THREAD

**Issue by listenaddress** [toranb/fly-pgvector#1]
Hey Toran! 

Thanks for creating this image—exactly what I need. 

When I run `flyctl postgres create --image-ref toranb/pgvector`, I get logs like this and the machine never becomes healthy. Any idea why I'm getting this?

```
panic: failed to initialize postgres failed to init postgres: exit status 1
```

Full logs

```
2024-01-08T00:54:04.458 app[080624ea592958] ord [info] INFO Starting init (commit: 15238e9)...
2024-01-08T00:54:04.483 app[080624ea592958] ord [info] INFO Mounting /dev/vdb at /data w/ uid: 0, gid: 0 and chmod 0755
2024-01-08T00:54:04.485 app[080624ea592958] ord [info] INFO Resized /data to 1056964608 bytes
2024-01-08T00:54:04.486 app[080624ea592958] ord [info] INFO Preparing to run: `docker-entrypoint.sh start` as root
2024-01-08T00:54:04.503 app[080624ea592958] ord [info] INFO [fly api proxy] listening at /.fly/api
2024-01-08T00:54:04.513 app[080624ea592958] ord [info] 2024/01/08 00:54:04 listening on [fdaa:3:bd7d:a7b:254:98bc:34fb:2]:22 (DNS: [fdaa::3]:53)
2024-01-08T00:54:04.691 app[080624ea592958] ord [info] Provisioning primary
2024-01-08T00:54:04.863 app[080624ea592958] ord [info] panic: failed to initialize postgres failed to init postgres: exit status 1
2024-01-08T00:54:04.863 app[080624ea592958] ord [info] goroutine 1 [running]:
2024-01-08T00:54:04.863 app[080624ea592958] ord [info] main.panicHandler({0x9a73a0?, 0xc0001caea0})
2024-01-08T00:54:04.863 app[080624ea592958] ord [info] /go/src/github.com/fly-apps/fly-postgres/cmd/start/main.go:188 +0x55
2024-01-08T00:54:04.863 app[080624ea592958] ord [info] main.main()
2024-01-08T00:54:04.863 app[080624ea592958] ord [info] /go/src/github.com/fly-apps/fly-postgres/cmd/start/main.go:65 +0xe5e
2024-01-08T00:54:05.504 app[080624ea592958] ord [info] INFO Main child exited normally with code: 2
2024-01-08T00:54:05.504 app[080624ea592958] ord [info] INFO Starting clean up.
```

**Comment by dev-xo** [comment]
Consider opening an issue on the Fly.io forum too, @listenaddress.

**Comment by toranb** [comment]
@listenaddress I took this back down to 15.2 and re-deployed. I then had no issues creating this on fly.io

Can you give this another try today and report back? Sorry for the half baked 15.3 deploy (was doing content over the weekend and left this incomplete)

**Comment by toranb** [comment]
let me know if that isn't working because although health checks are valid 3/3 I see this in the logs which is odd

`failed: FATAL: role "repmgr" does not exist`

**Comment by listenaddress** [comment]
You're a saint @toranb, I'm up and running.
